import React, { useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [responseData, setResponseData] = useState();
  const titleRef = useRef();
  const feedbackRef = useRef();

  const handleSubmit = async (event) => {
    event.preventDefault();
    const title = titleRef.current.value;
    const text = feedbackRef.current.value;

    const request = {
      title,
      text,
    };
    const url = "http://localhost:3000/api/feedback";
    axiosPost(url, request);
  };

  const axiosPost = async (url, obj) => {
    try {
      const res = await axios.post(url, obj);
      const data = await JSON.parse(res.data.data)
      console.log(data)
      setResponseData(data[0].title)
      
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="title">Title</label>
            <input
              ref={titleRef}
              id="title"
              type="text"
              placeholder="feedback title"
            />
          </div>
          <div>
            <label htmlFor="feedback">Feedback</label>
            <input
              ref={feedbackRef}
              id="feedback"
              type="textarea"
              placeholder="feedback here"
            />
          </div>
          <button type="submit">submit</button>
        </form>
        <div>{responseData}</div>
      </main>
    </>
  );
}
